version: '3.9'

services:
  testcontainers-go-workshop:
    build:
      context: ""
      dockerfile: Dockerfile 
    ports:
      - 3000:3000
    env_file:
      - "./.env"
    
  db:
    image: mariadb:10.5.8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "books"
    volumes:
      - ./seed/init.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: elasticsearch:7.17.6
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - esnet
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "-u", "elastic:changeme", "http://localhost:9200/_cat/health"]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    environment:
      - "ELASTICSEARCH_PASSWORD=changeme"
      - server.port=127.0.0.1:5601
      - elasticsearch.url="http://elasticsearch:9200"
      - server.name="kibana"
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
      retries: 6
    networks:
      - esnet
    depends_on:
      - elasticsearch

  configure_elasticsearch:
     image: docker.elastic.co/beats/metricbeat:7.17.6
     environment:
        - 'ELASTIC_VERSION=7.17.6'
        - 'ES_PASSWORD=changeme'
     volumes:
        - './seed/es/es_init.sh:/usr/local/bin/configure-stack.sh:ro'
        - './seed/es/data.json:/usr/local/bin/data.json'
        - './seed/es/books_temp.json:/usr/local/bin/books_temp.json'
     command: ['/bin/bash', '-c', 'cat /usr/local/bin/configure-stack.sh | tr -d "\r" | bash']
     networks:
       - 'esnet'
     depends_on:
        - 'elasticsearch'
        - 'kibana'

networks:
  esnet:
      driver: bridge
