version: '3.9'

services:
  testcontainers-go-workshop:
    build:
      context: ""
      dockerfile: Dockerfile 
    ports:
      - 3000:3000
    env_file:
      - "./.env"
    
  db:
    image: mariadb:10.5.8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "books"
    volumes:
      - ./seed/init.sql:/docker-entrypoint-initdb.d/init.sql